server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/oauth2-oidc-example
            user-name-attribute: preferred_username
        registration:
          greetings-app-client-credentials:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: greetings-client
            client-secret: BUqnWzi4y0LdAWmh5VbY5oXug49LBGsy
            scope:
              - greetings
          greetings-app-authorization-code:
            provider: keycloak
            client-id: greetings-client
            client-secret: BUqnWzi4y0LdAWmh5VbY5oXug49LBGsy
            scope:
              - openid
              - microprofile-jwt